apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamflix.fullname" . }}-config
data:
  API_PORT: {{ .Values.api.port | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  MEDIA_PUBLIC_BASE_URL: {{ .Values.config.mediaPublicBaseUrl | quote }}
