{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: streamflix-aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.config.s3Region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: streamflix-api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamflix-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: streamflix-aws-secrets
    kind: SecretStore
  target:
    name: streamflix-app-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.secretName | quote }}
{{- end }}
