{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streamflix.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | quote }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | quote }}
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - {{- if .Values.ingress.host }}host: {{ .Values.ingress.host }}{{- end }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: streamflix-api
            port: { number: 4000 }
      - path: /
        pathType: Prefix
        backend:
          service:
            name: streamflix-web
            port: { number: 80 }
{{- end }}
