apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamflix-api
  annotations:
    {{- if .Values.serviceAccounts.apiRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.apiRoleArn | quote }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streamflix-worker
  annotations:
    {{- if .Values.serviceAccounts.workerRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.workerRoleArn | quote }}
    {{- end }}
