# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "streamflix-terraform-state-501380833508"
    dynamodb_table = "streamflix-terraform-lock"
    encrypt        = true
    key            = "streamflix/dev/./terraform.tfstate"
    region         = "ap-south-1"
  }
}
