name: StreamFlix CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: API syntax
        working-directory: apps/api
        run: npm install && node --check src/server.js

      - name: Worker syntax
        working-directory: apps/worker
        run: npm install && node --check src/worker.js

      - name: Web build
        working-directory: apps/web
        run: npm ci && npm run build

      - name: Helm lint
        uses: azure/setup-helm@v4
        with:
          version: v3.18.6
      - run: helm lint helm/streamflix
